import { useState, useEffect } from 'react';
import {
    FileText, Search, Eye, Download, Calendar, User, Pill,
    X, Brain, Filter, Shield, AlertCircle, Activity
} from 'lucide-react';
import { doctorService } from '../services/doctorService';

export function PrescriptionRecords() {
    const [prescriptions, setPrescriptions] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');
    const [filter, setFilter] = useState('All');
    const [customDate, setCustomDate] = useState('');
    const [selectedRx, setSelectedRx] = useState<any | null>(null);

    useEffect(() => {
        fetchPrescriptions();
    }, [filter, customDate]);

    const fetchPrescriptions = async () => {
        setLoading(true);
        try {
            let data = await doctorService.getDoctorPrescriptions(
                filter,
                filter === 'Custom' ? customDate : undefined
            );
            
            setPrescriptions(data || []);
        } catch (error) {
            console.error('Error fetching prescriptions:', error);
            setPrescriptions([]);
        } finally {
            setLoading(false);
        }
    };

    const filtered = (prescriptions || []).filter(rx => {
        const patientName = rx.patient?.full_name?.toLowerCase() || '';
        const rxId = rx.prescription_id?.toString().toLowerCase() || '';
        const lowerSearch = searchTerm.toLowerCase();
        return patientName.includes(lowerSearch) || rxId.includes(lowerSearch);
    });

    return (
        <div className="p-4 sm:p-6 space-y-6 bg-gray-50 min-h-screen">
            {/* Header */}
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900">Prescription Records</h1>
                    <p className="text-gray-500">History of prescriptions generated by you</p>
                </div>
                <div className="flex items-center gap-2 text-green-600 bg-green-50 px-4 py-2 rounded-xl border border-green-100">
                    <Shield className="w-5 h-5" />
                    <span className="text-sm font-bold">Strict Doctor Isolation Active</span>
                </div>
            </div>

            {/* AI Insights (Static Mock for UI Wow factor) */}
            <div className="bg-gradient-to-r from-blue-600 to-indigo-700 rounded-2xl p-6 text-white shadow-lg relative overflow-hidden">
                <div className="relative z-10 flex items-start gap-4">
                    <div className="p-3 bg-white/20 backdrop-blur-md rounded-xl">
                        <Brain className="w-8 h-8 text-white" />
                    </div>
                    <div className="flex-1">
                        <h3 className="text-xl font-bold mb-2">Automated Rx Intelligence</h3>
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <InsightItem label="Medication Adherence" value="92%" />
                            <InsightItem label="Drug Safety Score" value="A+" />
                            <InsightItem label="Interaction Alerts" value="0 High Risk" />
                        </div>
                    </div>
                </div>
                <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-3xl -mr-32 -mt-32"></div>
            </div>

            {/* Controls Row */}
            <div className="bg-white rounded-2xl border border-gray-200 p-4 shadow-sm flex flex-col lg:flex-row gap-4">
                <div className="relative flex-1">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                    <input
                        type="text"
                        placeholder="Search by patient name or Rx ID..."
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="w-full pl-10 pr-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm outline-none focus:ring-2 focus:ring-blue-500 transition-all font-medium"
                    />
                </div>

                <div className="flex flex-wrap gap-2">
                    <div className="flex bg-gray-100 p-1 rounded-xl">
                        {['All', 'Today', 'Yesterday', 'Custom'].map(f => (
                            <button
                                key={f}
                                onClick={() => setFilter(f)}
                                className={`px-5 py-1.5 rounded-lg text-xs font-bold transition-all ${filter === f ? 'bg-white text-blue-600 shadow-sm' : 'text-gray-500 hover:text-gray-700'
                                    }`}
                            >
                                {f}
                            </button>
                        ))}
                    </div>

                    {filter === 'Custom' && (
                        <input
                            type="date"
                            value={customDate}
                            onChange={(e) => setCustomDate(e.target.value)}
                            className="px-4 py-1.5 bg-white border border-gray-200 rounded-xl text-xs font-bold outline-none focus:ring-2 focus:ring-blue-500 shadow-sm"
                        />
                    )}

                    <button onClick={fetchPrescriptions} className="p-2.5 bg-blue-600 text-white rounded-xl hover:bg-blue-700 shadow-md">
                        <Filter className="w-4 h-4" />
                    </button>
                </div>
            </div>

            {/* List */}
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
                {loading ? (
                    <div className="col-span-full py-20 flex justify-center">
                        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
                    </div>
                ) : filtered.length === 0 ? (
                    <div className="col-span-full py-20 flex flex-col items-center justify-center text-gray-400 bg-white rounded-2xl border border-dashed border-gray-300">
                        <FileText className="w-16 h-16 mb-4 opacity-10" />
                        <p className="font-bold text-lg">No records found for this period</p>
                        <p className="text-sm">Ensure filters are set correctly or create new prescriptions from Appointment Management.</p>
                    </div>
                ) : (
                    filtered.map(rx => (
                        <PRCard key={rx.prescription_id} rx={rx} onClick={() => setSelectedRx(rx)} />
                    ))
                )}
            </div>

            {/* Details Modal */}
            {selectedRx && (
                <div className="fixed inset-0 bg-black/60 backdrop-blur-md flex items-center justify-center z-50 p-4">
                    <div className="bg-white rounded-3xl max-w-2xl w-full shadow-2xl animate-in fade-in zoom-in duration-200 overflow-hidden">
                        <div className="p-6 bg-gradient-to-r from-blue-600 to-blue-800 text-white flex justify-between items-center">
                            <div>
                                <h2 className="text-xl font-bold flex items-center gap-2">
                                    <FileText className="w-6 h-6" />
                                    Prescription Record
                                </h2>
                                <p className="text-blue-100 text-xs font-medium uppercase tracking-widest mt-1">Ref No: {selectedRx.prescription_id}</p>
                            </div>
                            <button onClick={() => setSelectedRx(null)} className="p-2 hover:bg-white/20 rounded-full transition-colors">
                                <X className="w-6 h-6" />
                            </button>
                        </div>

                        <div className="p-8 space-y-8 overflow-y-auto max-h-[70vh]">
                            {/* Patient Demographics */}
                            <div className="grid grid-cols-2 md:grid-cols-3 gap-6">
                                <DetailBox label="Patient Name" value={selectedRx.patient?.full_name} icon={<User className="w-4 h-4" />} />
                                <DetailBox label="Patient ID" value={selectedRx.patient_id} />
                                <DetailBox label="Age / Gender" value={`${selectedRx.patient?.age || 'N/A'} / ${selectedRx.patient?.gender || 'N/A'}`} />
                                <DetailBox label="Blood Group" value={selectedRx.patient?.blood_group} color="text-red-600" />
                                <DetailBox label="ABHA ID" value={selectedRx.patient?.abha_id || 'Not Linked'} />
                                <DetailBox label="Insurance ID" value={selectedRx.patient?.insurance_id || 'N/A'} />
                            </div>

                            {/* Contact Information */}
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-4 bg-gray-50 rounded-2xl border border-gray-100">
                                <DetailBox label="Phone Number" value={selectedRx.patient?.phone} />
                                <DetailBox label="Email Address" value={selectedRx.patient?.email} />
                                <div className="md:col-span-2">
                                    <DetailBox label="Residential Address" value={selectedRx.patient?.address} />
                                </div>
                            </div>

                            {/* Prescription Timeline */}
                            <div className="grid grid-cols-2 md:grid-cols-3 gap-6">
                                <DetailBox label="Date Generated" value={new Date(selectedRx.created_at).toLocaleDateString()} icon={<Calendar className="w-4 h-4" />} />
                                <DetailBox label="Follow-up Date" value={selectedRx.follow_up_date ? new Date(selectedRx.follow_up_date).toLocaleDateString() : 'No Follow-up'} color="text-orange-600" />
                                <DetailBox label="Visit Type" value={selectedRx.appointments?.type || 'Consultation'} />
                            </div>

                            {selectedRx.patient?.medical_history && (
                                <div className="space-y-3">
                                    <h4 className="text-sm font-black text-gray-900 uppercase tracking-widest flex items-center gap-2">
                                        <Activity className="w-4 h-4 text-red-600" />
                                        Patient Medical History
                                    </h4>
                                    <div className="p-4 bg-red-50/50 rounded-2xl border border-red-100 text-gray-700 italic">
                                        {selectedRx.patient.medical_history}
                                    </div>
                                </div>
                            )}

                            {selectedRx.patient?.patient_documents && selectedRx.patient.patient_documents.length > 0 && (
                                <div className="space-y-4">
                                    <h4 className="text-sm font-black text-gray-900 uppercase tracking-widest flex items-center gap-2">
                                        <FileText className="w-4 h-4 text-indigo-600" />
                                        Uploaded Medical Reports
                                    </h4>
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                        {selectedRx.patient.patient_documents.map((doc: any, i: number) => (
                                            <a key={i} href={doc.file_url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 p-3 bg-white rounded-xl border border-gray-200 hover:border-indigo-300 transition-colors group">
                                                <div className="p-2 bg-indigo-50 text-indigo-600 rounded-lg group-hover:bg-indigo-600 group-hover:text-white transition-colors">
                                                    <FileText className="w-4 h-4" />
                                                </div>
                                                <div>
                                                    <p className="text-sm font-bold text-gray-900 line-clamp-1">{doc.document_type || doc.file_name || 'Medical Report'}</p>
                                                    <p className="text-xs text-gray-500">View Document</p>
                                                </div>
                                            </a>
                                        ))}
                                    </div>
                                </div>
                            )}

                            <div className="space-y-3">
                                <h4 className="text-sm font-black text-gray-900 uppercase tracking-widest flex items-center gap-2">
                                    <Shield className="w-4 h-4 text-blue-600" />
                                    Clinical Diagnosis
                                </h4>
                                <div className="p-4 bg-blue-50/50 rounded-2xl border border-blue-100 text-gray-700 italic">
                                    {selectedRx.diagnosis || 'No diagnosis recorded'}
                                </div>
                            </div>

                            <div className="space-y-4">
                                <h4 className="text-sm font-black text-gray-900 uppercase tracking-widest flex items-center gap-2">
                                    <Pill className="w-4 h-4 text-purple-600" />
                                    Medications ({selectedRx.medicines?.length || 0})
                                </h4>
                                <div className="space-y-3">
                                    {selectedRx.medicines?.map((m: any, i: number) => (
                                        <div key={i} className="flex justify-between items-center p-4 bg-gray-50 rounded-2xl border border-gray-100">
                                            <div>
                                                <p className="font-bold text-gray-900">{m.medicine_name}</p>
                                                <p className="text-xs text-gray-500">{m.frequency} • {m.duration}</p>
                                            </div>
                                            <div className="text-right">
                                                <p className="text-sm font-black text-blue-600">{m.dosage}</p>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {selectedRx.notes && (
                                <div className="space-y-3">
                                    <h4 className="text-sm font-black text-gray-900 uppercase tracking-widest flex items-center gap-2">
                                        <AlertCircle className="w-4 h-4 text-orange-500" />
                                        Special Instructions
                                    </h4>
                                    <p className="text-sm text-gray-600 leading-relaxed px-4 border-l-4 border-orange-200">
                                        {selectedRx.notes}
                                    </p>
                                </div>
                            )}
                        </div>

                        <div className="p-6 bg-gray-50 border-t border-gray-200 flex gap-4">
                            <button className="flex-1 py-3 bg-blue-600 text-white rounded-2xl font-bold hover:bg-blue-700 flex items-center justify-center gap-2 shadow-lg">
                                <Download className="w-5 h-5" />
                                Download PDF
                            </button>
                            <button onClick={() => setSelectedRx(null)} className="px-8 py-3 bg-white border border-gray-200 text-gray-700 rounded-2xl font-bold hover:bg-gray-100">
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}

function PRCard({ rx, onClick }: any) {
    return (
        <div 
            onClick={onClick}
            className="bg-white rounded-2xl border border-gray-200 p-6 hover:shadow-xl transition-all group overflow-hidden relative cursor-pointer active:scale-[0.98]"
        >
            <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                <FileText className="w-16 h-16 text-blue-600" />
            </div>

            <div className="flex justify-between items-start mb-6">
                <div className="flex items-center gap-4">
                    <div className="w-14 h-14 bg-blue-100 rounded-2xl flex items-center justify-center group-hover:bg-blue-600 transition-colors">
                        <User className="w-7 h-7 text-blue-600 group-hover:text-white transition-colors" />
                    </div>
                    <div>
                        <h3 className="text-lg font-bold text-gray-900 group-hover:text-blue-600 transition-colors">{rx.patient?.full_name}</h3>
                        <p className="text-xs font-bold text-gray-500 uppercase">ID: {rx.patient_id}</p>
                    </div>
                </div>
                <div className="p-2 bg-gray-50 group-hover:bg-blue-600 text-gray-400 group-hover:text-white rounded-xl border border-gray-100 transition-all">
                    <Eye className="w-5 h-5" />
                </div>
            </div>

            <div className="flex flex-wrap gap-4 mb-6">
                <div className="flex items-center gap-2 text-xs font-bold text-gray-500 bg-gray-100 px-3 py-1.5 rounded-lg">
                    <Calendar className="w-3.5 h-3.5" />
                    {new Date(rx.created_at).toLocaleDateString()}
                </div>
                <div className="flex items-center gap-2 text-xs font-bold text-purple-600 bg-purple-50 px-3 py-1.5 rounded-lg">
                    <Pill className="w-3.5 h-3.5" />
                    {rx.medicines?.length || 0} Medications
                </div>
            </div>

            <div className="p-4 bg-gray-50/80 rounded-2xl border border-gray-100 group-hover:bg-white transition-colors">
                <p className="text-xs font-black text-gray-400 uppercase tracking-widest mb-1">Diagnosis</p>
                <p className="text-sm font-medium text-gray-700 line-clamp-2">{rx.diagnosis || 'No summary diagnosis'}</p>
            </div>
        </div>
    );
}

function DetailBox({ label, value, icon, color }: any) {
    return (
        <div className="space-y-1">
            <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">{label}</p>
            <div className={`flex items-center gap-2 text-gray-900 font-bold ${color || ''}`}>
                {icon}
                {value || 'N/A'}
            </div>
        </div>
    );
}

function InsightItem({ label, value }: any) {
    return (
        <div className="bg-white/10 backdrop-blur-sm rounded-xl p-3 border border-white/5">
            <p className="text-[10px] font-bold text-blue-100 uppercase mb-1">{label}</p>
            <p className="text-lg font-black">{value}</p>
        </div>
    );
}
